events {
    worker_connections 1024;
}

http {
    upstream backend_lc {
        least_conn;
        server upstream-s0:8000;
        server upstream-s1:8000;
        server upstream-s2:8000;
        server upstream-s3:8000;
        server upstream-s4:8000;
        server upstream-s5:8000;
    }

    server {
        listen 80;

        location /api/work {
            proxy_pass http://backend_lc/api/work;
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }

        location /admin/ {
            proxy_pass http://backend_lc;
        }

        location /health {
            return 200 '{"status":"ok","balancer":"nginx-lc"}';
            add_header Content-Type application/json;
        }
    }
}
